default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>

development:
  adapter: sqlite3
  database: tmp/klaxon.sqlite

test:
  <<: *default
  database: klaxon_test
  username: <%= ENV['PGUSER'] || `whoami` %>
  password: <%= ENV['PGPASSWORD'] %>
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
